export const TOKEN_COOKIE_NAME = 'token'
export const ROLE_ADMIN = 'ROLE_ADMIN'
export const ROLE_STUDENT = 'ROLE_STUDENT'
export const ROLE_TEACHER = 'ROLE_TEACHER'
export const ROLE_PARENT = 'ROLE_PARENT'