export const USERNAME_REGEX = '^([A-Za-z0-9]{5,20})$'
export const PASSWORD_REGEX = '^(?=.*[a-zA-Z0-9])[a-zA-Z0-9]{5,10}$'
export const EMAIL_REGEX = '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$'
export const PERSON_NAME_REGEX = '^([A-Z][a-z]+\\s[A-Z][a-z]+)$'
export const PIN_REGEX = '^([0-9]{2}([0][1-9]|[1][0-2])([0][1-9]|[1-2][0-9]|[3][0-1])([0-9]){4})$'
export const SCHOOL_SUBJECT_NAME_REGEX = '^([A-Z][a-z]+)$'
export const GROUP_OF_STUDENTS_NAME_REGEX = '^([1-9][a-z]|[1][0-2][a-z])$'